[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/awb"
  to = "/.netlify/functions/awb"
  status = 200
  force = true

[[redirects]]
  from = "/api/track"
  to = "https://omanair.smartkargo.com/FrmAWBTracking.aspx"
  status = 200
  force = true
